# Generated by Django 4.1.2 on 2023-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="products/default-image.jpg",
                help_text="Upload a product image",
                upload_to="products/%Y/%m/%d",
                verbose_name="Image",
            ),
        ),
    ]
