# Generated by Django 4.1.2 on 2023-01-25 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0002_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user_wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
